services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB:
      POSTGRES_PASSWORD:
      POSTGRES_USER:
    ports:
      - 5432:5432
    volumes:
      - 'webdb:/var/lib/postgresql/data'

volumes:
  webdb:
